const { Command } = require('discord-akairo');
const Discord = require('discord.js')
const chalk = require('chalk');


class KeyCommand extends Command {
    constructor() {
        super('key', {
            aliases: ['key'],
            channel: 'guild',
            category: 'Utilities',
            description: {
                content: 'Generates useless random 16 digit Alpha Numeric key.'
            },

        });
    }

    async exec(message) {

        console.log(chalk.green('key was generated by ' + chalk.yellow(message.author.username)));

        function makeid(length) {
            var result = [];
            var characters = 'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789';
            var charactersLength = characters.length;
            for (var i = 0; i < length; i++) {
                result.push(characters.charAt(Math.floor(Math.random() *
                    charactersLength)));
            }
            return result.join('');
        }
        const embed = new Discord.MessageEmbed()
            .setTitle("Your random key!!")
            .setDescription(`${makeid(4).toUpperCase()}-` + `${makeid(4).toUpperCase()}-` + `${makeid(4).toUpperCase()}-` + `${makeid(4).toUpperCase()}`)
            .setColor('#1b51be')
            .setThumbnail('https://freepngimg.com/thumb/key/36710-1-key-clipart.png')
        try {
            message.channel.send({ embed });
        }
        catch (rej) {
            message.channel.send("Sorry, I was unable to process this command. Make sure that I have full send permissions for embeds and messages and then try again!");
            console.log(chalk.red('Error in sending random key' + chalk.cyan(rej)));
        }

    }
}

module.exports = KeyCommand;

